const BackMapType = {
  NOT_SET: 0,

  OPENSTREETMAP: 1,
  OSM: 1,

  GOOGLE_SATELLITE: 21,
  GOOGLE_ROADMAP: 22,
  GOOGLE_HYBRID: 23,
  GOOGLE_TERRAIN: 24,

  TIANDITU_NORMAL_MAP: 31,
  TIANDITU_SATELLITE_MAP: 32,
  TIANDITU_HYBRID_MAP: 33,
  TIANDITU_TERRAIN_MAP: 34,
  TIANDITU_TERRAIN_HYBRID_MAP: 35,

  GAODE_STANDARD: 41,
  GAODE_SATELLITE: 42,
  GAODE_ROADNET: 43,
  GAODE_TRAFFIC: 44,
  GAODE_ROADNET_SATELLITE: 45,

  BING_ROADMAP: 51,
  BING_SATELLITE: 52,

  BAIDU_NORMAL_MAP: 61,
  BAIDU_SATELLITE_MAP: 62,
  BAIDU_HYBRID_MAP: 63,

  QQ_ROAD: 71,
  QQ_SATELLITE: 72,
  QQ_ROAD_SATELLITE: 73,
  QQ_TRAFFIC: 74
}

export default BackMapType
